/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  }),
  'date' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func(
      [
        IDL.Variant({ 'expense' : IDL.Null, 'income' : IDL.Null }),
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getBudgets' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryBreakdown' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalIncome' : IDL.Float64,
          'totalExpenses' : IDL.Float64,
          'netBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Variant({
      'expense' : IDL.Null,
      'income' : IDL.Null,
    }),
    'date' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func(
        [
          IDL.Variant({ 'expense' : IDL.Null, 'income' : IDL.Null }),
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getBudgets' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryBreakdown' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalIncome' : IDL.Float64,
            'totalExpenses' : IDL.Float64,
            'netBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };